---
# Theme 02: Rocky Linux Advanced Security Controls
- name: Rocky Linux Security Controls
  hosts: rocky
  become: yes
  tasks:
    # Fix EPEL repository issues
    - name: Install EPEL repository
      dnf:
        name: epel-release
        state: present
        disable_gpg_check: yes
      register: epel_result
      ignore_errors: yes
      
    - name: Configure EPEL repository manually if installation fails
      block:
        - name: Create EPEL repo file
          copy:
            dest: /etc/yum.repos.d/epel.repo
            content: |
              [epel]
              name=Extra Packages for Enterprise Linux $releasever - $basearch
              metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch
              failovermethod=priority
              enabled=1
              gpgcheck=0
            mode: '0644'
          when: epel_result is failed
          
        - name: Clean DNF cache
          command: dnf clean all
          when: epel_result is failed
          
        - name: Update DNF cache
          command: dnf makecache
          when: epel_result is failed
      when: epel_result is failed

    # System Administration
    - name: Install logrotate if not present
      dnf:
        name: logrotate
        state: present

    - name: Create custom logrotate configuration
      copy:
        dest: /etc/logrotate.d/custom_syslog
        content: |
          /var/log/messages {
            rotate 7
            daily
            compress
            notifempty
            missingok
          }
        mode: '0644'
      
    - name: Create health check script
      copy:
        dest: /usr/local/bin/health_check.sh
        content: |
          #!/bin/bash
          echo "=== System Health Check $(date) ==="
          echo "=== Disk Usage ==="
          df -h
          echo "=== Memory Usage ==="
          free -m
          echo "=== CPU Load ==="
          uptime
          echo "=== Active Services ==="
          systemctl list-units --type=service --state=running
        mode: '0755'
        
    - name: Set up regular system health checks
      cron:
        name: "System health check"
        minute: "0"
        hour: "*/4"
        job: "/usr/local/bin/health_check.sh > /var/log/health_check.log 2>&1"
        
    # System Hardening
    - name: Install password quality package
      dnf:
        name: libpwquality
        state: present
        
    - name: Configure password policies
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        create: yes
      loop:
        - { regexp: '^# minlen', line: 'minlen = 12' }
        - { regexp: '^# dcredit', line: 'dcredit = -1' }
        - { regexp: '^# ucredit', line: 'ucredit = -1' }
        - { regexp: '^# lcredit', line: 'lcredit = -1' }
        - { regexp: '^# ocredit', line: 'ocredit = -1' }
      
    - name: Enable and configure auditd
      block:
        - name: Install audit package
          dnf:
            name: audit
            state: present
            
        - name: Create custom audit rules directory if it doesn't exist
          file:
            path: /etc/audit/rules.d
            state: directory
            mode: '0750'
            
        - name: Configure basic audit rules
          copy:
            dest: /etc/audit/rules.d/custom.rules
            content: |
              # Log authentication events
              -w /var/log/secure -p wa -k authentication
              # Monitor sudo usage
              -w /etc/sudoers -p wa -k sudoers
            mode: '0640'
            
        - name: Enable and start auditd service
          service:
            name: auditd
            state: started
            enabled: yes
      rescue:
        - name: Log failure
          debug:
            msg: "Failed to configure audit service"
